name: "Close Stale Issues"

on:
  schedule:
    - cron:
        "0 5 * * *"
        #MIN HOUR DOM MON DOW CMD

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # need to regenerate everything before merge...
      #    regenerate NEXT.json [can have multiple PRs not merged at the same time...]
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: context
        run: |
          echo "github.actor ${{ github.actor }}"
          echo "github.event.repository.owner.login ${{ github.event.repository.owner.login }}"
      - name: Checking Stale PRs
        uses: next-cpan/next-ci-action@master
        with:
          stage: cron_stale
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BOT_ACCESS_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
