on: issue_comment
name: Issue Comments

# https://github.com/xt0rted/slash-command-action
#   also view https://github.com/peter-evans/slash-command-dispatch

jobs:

  check_comments:
    runs-on: ubuntu-latest
    name: Check comments for /test
    if: github.repository_owner == 'next-cpan' && github.event.issue.pull_request != null
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      # command
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: test
          reaction: "true"
          reaction-type: "rocket"
          allow-edits: "false"
          permission-level: admin
      - name: Act on the command
        run: echo "The command was '${{ steps.command.outputs.command-name }}' with arguments '${{ steps.command.outputs.command-arguments }}'"
      - run: echo "${{ github.repository_owner }}"
      - run: echo "Continue"
      ## dump
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"


  lint:
    needs: check_comments

    name: Running lint checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: context
        run: |
          echo "github.actor ${{ github.actor }}"
          echo "github.event.repository.owner.login ${{ github.event.repository.owner.login }}"
      - name: "running lint..."
        run: |
          echo "rebase..."
          echo "Confirm no generated files are altered"
          echo "Update the NEXT.json using .next/hints.yaml"
          echo "Assure VERSION not bumped in NEXT.json"
          echo "Check no new modules owned by other distros"
          true
      # maybe push to a local branch check_pr_$id so unit tests can start using it
      - name: Checking Pull Request
        uses: next-cpan/next-ci-action@master
        with:
          stage: lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BOT_ACCESS_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}